### ISSUE TITLE
Behavior issues

### ISSUE THREAD

**Issue by ghost** [GleasonK/Polymer-Todo#2]
The error I recieved: Received firebase-child-removed event for unknown child "-K-N1yz28CTfACATYlNW"'

I connected two devices to a depolyed(to firebase) version of your repo, using the same google account on each device.  When one deleted an item the other device threw the error above.

I cloned your repo, bower update, changed the firebase element from your firebase to mine, ran gulp and then firebase deployed it to my firebase after editing firebase.json. Those are the only changes I made.

Also shows up for editing: Received firebase-child-changed event for unknown child "-K-N56Pd9ebRqLPGBsHo"

I assume it wasn't meant to be used this way since probably each account should only be active on one device but if you have a simple fix it would be a nice feature to have. I believe it may be the firebase object id changes.

It seems as if it doesnt show up all the time either. Might be a race condition.

**Comment by GleasonK** [comment]
This repo doesn't use a firebase element? It uses PubNub to manage the real-time synchronization.

**Comment by ghost** [comment]
My apologies I posted this on the wrong to-do Github repo
